name: Run Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/CI.yml'
      - '.github/workflows/TagBot.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/CI.yml'
      - '.github/workflows/TagBot.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
jobs:
  test:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.11', '1.12', 'pre']
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-runtest@v1
        with: 
          test_args: "--backend=CPU --CI"
